-- =============================================================================
-- Migration 32: HIGH-1 — Restrict profiles visibility
-- Generated by: mind-manual-progress Run 20 (2026-06-30)
-- Severity: HIGH
--
-- Problem: "Profiles are viewable by everyone" uses USING (true), exposing
-- all users' email, display_name, avatar_url, email_verified to any
-- unauthenticated request. For a mental health app, even knowing who uses
-- the app is sensitive (stigma, disclosure risk).
--
-- Fix: Replace with own-profile-only SELECT (Option A).
-- Option B (authenticated-users-can-see-basic-info) is commented below —
-- enable only if the app develops social/friend features.
-- =============================================================================

DROP POLICY IF EXISTS "Profiles are viewable by everyone" ON public.profiles;

-- Option A (RECOMMENDED): users can only read their own profile
CREATE POLICY "Users read own profile"
  ON public.profiles FOR SELECT
  USING (auth.uid() = id);

-- Option B (social app variant — NOT enabled):
-- CREATE POLICY "Authenticated users read profiles"
--   ON public.profiles FOR SELECT
--   USING (auth.role() = 'authenticated');
