-- =============================================================================
-- Migration 31: CRITICAL-2 — Fix photos storage bucket policies
-- Generated by: mind-manual-progress Run 20 (2026-06-30)
-- Severity: CRITICAL
--
-- Problem: The photos bucket is public=true and has "Allow photo *" policies
-- from migration 20250826083014 with NO auth check — anonymous users can
-- upload, update, and delete ANY user's photos. Prior "Users can manage" policies
-- from 20250826053550 are also over-broad (UPDATE/DELETE check only auth.role(),
-- not user path). Neither set was dropped.
--
-- Before applying: Confirm all photo upload paths use {user_id}/{filename} format
-- in BubbleCard.tsx or equivalent components. The path-based policies rely on this.
-- =============================================================================

-- Step 1: Drop ALL existing photos bucket policies (both migration sets)
DROP POLICY IF EXISTS "Anyone can view photos"                 ON storage.objects;
DROP POLICY IF EXISTS "Authenticated users can upload photos"  ON storage.objects;
DROP POLICY IF EXISTS "Users can update their own photos"      ON storage.objects;
DROP POLICY IF EXISTS "Users can delete their own photos"      ON storage.objects;
DROP POLICY IF EXISTS "Allow photo uploads"                    ON storage.objects;
DROP POLICY IF EXISTS "Allow photo reads"                      ON storage.objects;
DROP POLICY IF EXISTS "Allow photo updates"                    ON storage.objects;
DROP POLICY IF EXISTS "Allow photo deletions"                  ON storage.objects;

-- Step 2: Make the bucket private (photos are personal mental-health content)
UPDATE storage.buckets
SET public = false
WHERE id = 'photos';

-- Step 3: Create correct user-scoped policies keyed on path prefix = user_id
-- All upload paths MUST be: {auth.uid()}/{filename}

CREATE POLICY "Users upload own photos"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'photos'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

CREATE POLICY "Users read own photos"
  ON storage.objects FOR SELECT
  USING (
    bucket_id = 'photos'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

CREATE POLICY "Users update own photos"
  ON storage.objects FOR UPDATE
  USING (
    bucket_id = 'photos'
    AND auth.uid()::text = (storage.foldername(name))[1]
  )
  WITH CHECK (
    bucket_id = 'photos'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );

CREATE POLICY "Users delete own photos"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'photos'
    AND auth.uid()::text = (storage.foldername(name))[1]
  );
