-- =============================================================================
-- Migration 35: MEDIUM-2 — Document sync_data / sync_logs append-only intent
-- Generated by: mind-manual-progress Run 20 (2026-06-30)
-- Severity: MEDIUM (documentation only — no policy change)
--
-- Problem: sync_data and sync_logs have no DELETE policies. This is intentional
-- CRDT design (conflicts resolved via server_clock ordering), but an auditor
-- seeing "no DELETE" without explanation might flag it. This migration adds
-- COMMENT ON TABLE to document the design decision.
--
-- GDPR compliance: account deletion cascades via ON DELETE CASCADE on the
-- auth.users FK — no user-level DELETE policy needed for erasure.
-- =============================================================================

COMMENT ON TABLE public.sync_data IS
  'CRDT-style append-only sync store. No DELETE policy by design — conflict resolution
  uses server_clock ordering; rows are never deleted in normal operation.
  GDPR compliance via ON DELETE CASCADE on user_id → auth.users.
  Do NOT add a user-facing DELETE policy without architectural review.';

COMMENT ON TABLE public.sync_logs IS
  'Append-only audit log for CRDT sync events. Same append-only design as sync_data.
  GDPR erasure handled by ON DELETE CASCADE on user_id → auth.users.';
