-- =============================================================================
-- Migration 33: HIGH-2 — Add DELETE policy to user_sessions (GDPR gap)
-- Generated by: mind-manual-progress Run 20 (2026-06-30)
-- Severity: HIGH
--
-- Problem: user_sessions has SELECT + INSERT + UPDATE policies scoped to
-- auth.uid() = user_id, but no DELETE policy. Users cannot revoke individual
-- sessions. GDPR Article 17 (right to erasure) allows granular deletion;
-- account-level cascade (ON DELETE CASCADE on auth.users FK) exists but
-- doesn't cover in-app session management.
-- =============================================================================

CREATE POLICY "Users can delete own sessions"
  ON public.user_sessions FOR DELETE
  USING (auth.uid() = user_id);
