-- =============================================================================
-- Migration 34: MEDIUM-1 — Add DELETE policy to conversation_summaries
-- Generated by: mind-manual-progress Run 20 (2026-06-30)
-- Severity: MEDIUM
--
-- Problem: conversation_summaries has SELECT + INSERT + UPDATE scoped to
-- auth.uid() = user_id, but no DELETE policy. Summaries may contain sensitive
-- mental health content; users should be able to delete their own.
-- =============================================================================

CREATE POLICY "Users can delete own conversation summaries"
  ON public.conversation_summaries FOR DELETE
  USING (auth.uid() = user_id);
