-- =============================================================================
-- Migration 30: CRITICAL-1 — Restrict plaid_items client access
-- Generated by: mind-manual-progress Run 20 (2026-06-30)
-- Severity: CRITICAL
-- 
-- Problem: The broad "FOR ALL USING (auth.uid() = user_id)" policy on plaid_items
-- permits authenticated clients to SELECT access_token directly — a plaintext
-- Plaid bank credential equivalent. Clients should never see access_token.
--
-- Fix A (this migration): Split into scoped SELECT/UPDATE policies + security-barrier
-- view (plaid_items_safe) that exposes only non-sensitive columns.
-- Fix B (migration 37, deferred): pgsodium encryption at rest.
--
-- Before applying: confirm PlaidIntegrationPlugin.tsx upload paths use user_id.
-- After applying: update PlaidIntegrationPlugin.tsx to query plaid_items_safe.
-- =============================================================================

-- Step 1: Drop the overly broad FOR ALL policy
DROP POLICY IF EXISTS "Users can manage their own Plaid items" ON public.plaid_items;

-- Step 2: Add scoped SELECT policy (no access_token column in view)
CREATE POLICY "Users can read own plaid_items metadata"
  ON public.plaid_items FOR SELECT
  USING (auth.uid() = user_id);

-- Step 3: Allow users to deactivate their own linked items
CREATE POLICY "Users can deactivate own plaid_items"
  ON public.plaid_items FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- No INSERT policy: edge function (plaid-exchange-token) uses service_role — correct.
-- No DELETE policy: disconnection goes through edge function — correct.

-- Step 4: Create a security-barrier view that excludes access_token + key_id
CREATE OR REPLACE VIEW public.plaid_items_safe
  WITH (security_invoker = true)
AS
  SELECT
    id,
    user_id,
    item_id,
    institution_name,
    is_active,
    created_at,
    updated_at
  FROM public.plaid_items
  WHERE auth.uid() = user_id;

-- Grant SELECT on view to authenticated users
GRANT SELECT ON public.plaid_items_safe TO authenticated;

-- Step 5: Revoke direct table SELECT from authenticated (force use of safe view)
-- Note: service_role always bypasses RLS and retains full access.
-- Uncomment this line after confirming PlaidIntegrationPlugin uses plaid_items_safe:
REVOKE SELECT ON public.plaid_items FROM authenticated;
