-- =============================================================================
-- Migration 36: LOW-1 — Add explicit WITH CHECK to all user-scoped FOR ALL policies
-- Generated by: mind-manual-progress Run 20 (2026-06-30)
-- Severity: LOW (code quality / auditability — no security hole)
--
-- Problem: 15 tables use FOR ALL USING (auth.uid() = user_id) without an
-- explicit WITH CHECK clause. PostgreSQL reuses the USING expression as WITH
-- CHECK for INSERTs/UPDATEs when omitted — semantically correct — but explicit
-- WITH CHECK is required for clean security audits and investor/compliance review.
--
-- Tables covered (service_role FOR ALL policies excluded — no behaviour change needed):
--   conversation_threads, public.calendar_accounts, public.calendar_events,
--   public.email_accounts, public.email_messages, public.email_recipients,
--   public.oauth_tokens, public.plaid_accounts, public.plaid_sync_status,
--   public.plaid_transactions, public.sync_conflicts, public.sync_devices,
--   public.webhook_subscriptions, user_memory
--
-- Note: public.plaid_items is handled by migration 30 (CRITICAL-1) — excluded here.
-- =============================================================================

-- conversation_threads
DROP POLICY IF EXISTS "Users can manage their own conversation threads" ON conversation_threads;
CREATE POLICY "Users can manage their own conversation threads"
  ON conversation_threads FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- public.calendar_accounts
DROP POLICY IF EXISTS "Users can manage their own calendar accounts" ON public.calendar_accounts;
CREATE POLICY "Users can manage their own calendar accounts"
  ON public.calendar_accounts FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- public.calendar_events
DROP POLICY IF EXISTS "Users can manage their own calendar events" ON public.calendar_events;
CREATE POLICY "Users can manage their own calendar events"
  ON public.calendar_events FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- public.email_accounts
DROP POLICY IF EXISTS "Users can manage their own email accounts" ON public.email_accounts;
CREATE POLICY "Users can manage their own email accounts"
  ON public.email_accounts FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- public.email_messages
DROP POLICY IF EXISTS "Users can manage their own email messages" ON public.email_messages;
CREATE POLICY "Users can manage their own email messages"
  ON public.email_messages FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- public.email_recipients
DROP POLICY IF EXISTS "Users can manage their own email recipients" ON public.email_recipients;
CREATE POLICY "Users can manage their own email recipients"
  ON public.email_recipients FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- public.oauth_tokens
DROP POLICY IF EXISTS "Users can manage their own tokens" ON public.oauth_tokens;
CREATE POLICY "Users can manage their own tokens"
  ON public.oauth_tokens FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- public.plaid_accounts
DROP POLICY IF EXISTS "Users can manage their own plaid accounts" ON public.plaid_accounts;
CREATE POLICY "Users can manage their own plaid accounts"
  ON public.plaid_accounts FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- public.plaid_sync_status
DROP POLICY IF EXISTS "Users can manage their own plaid sync status" ON public.plaid_sync_status;
CREATE POLICY "Users can manage their own plaid sync status"
  ON public.plaid_sync_status FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- public.plaid_transactions
DROP POLICY IF EXISTS "Users can manage their own plaid transactions" ON public.plaid_transactions;
CREATE POLICY "Users can manage their own plaid transactions"
  ON public.plaid_transactions FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- public.sync_conflicts (appears in two migrations — DROP IF EXISTS handles both)
DROP POLICY IF EXISTS "Users can manage their own conflicts" ON public.sync_conflicts;
CREATE POLICY "Users can manage their own conflicts"
  ON public.sync_conflicts FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- public.sync_devices (appears in two migrations — DROP IF EXISTS handles both)
DROP POLICY IF EXISTS "Users can manage their own devices" ON public.sync_devices;
CREATE POLICY "Users can manage their own devices"
  ON public.sync_devices FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- public.webhook_subscriptions
DROP POLICY IF EXISTS "Users can manage their own webhook subscriptions" ON public.webhook_subscriptions;
CREATE POLICY "Users can manage their own webhook subscriptions"
  ON public.webhook_subscriptions FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- user_memory
DROP POLICY IF EXISTS "Users can manage their own memory" ON user_memory;
CREATE POLICY "Users can manage their own memory"
  ON user_memory FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);
