// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekekeywoxvdbfbmqyhjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrZWtleXdveHZkYmZibXF5aGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzAzMjEsImV4cCI6MjA2NTkwNjMyMX0.RWQLDArXOK5eQFw1o5O42rUABYVWlEO2V5huz_i0GN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});